config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home', as: "home"
  get 'pages/projects', as: "projects"
  get 'pages/blog', as: "blog"
  get 'pages/contact', as: "contact"
  get 'pages/about', as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # skip_before_action :authenticate_user!, only: [:home]
  
    def home
    end

    def about
    end 

    def contact
    end 

    def blog
    end 
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lauranpham</title>
    <link rel="shortcut icon" href="images/profile_photo.JPG" />
    <meta name="description" content= "Development Portfolio of Laura Pham">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="application.scss">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">
<h1>About Me</h1>
    <div id="section">
    <div class="about-card">
      <h2>Full Stack Developer 💻</h2>
      <p class="description">A Full Stack Developer working in Education Tech. I enjoy the constant learning process, problem solving,
        creativity and opportunities to work with passionate, likeminded people.</p>
    </div>

    <div class="about-card">
      <h2>Teacher 📚</h2>
      <p class="description">I worked as a Science and Math teacher for three years. I hope to still make
      an impact in education through my role as a developer.</p>
    </div>

    <div class="about-card">
      <h2>Traveller 🌏</h2>
      <p class="description">Like every Australian, I am an avid world traveller. 20 countries and counting!
      I moved to London 10 months ago!</p>
    </div>
  </div>
</div>

app/views/pages/blog.html.erb
<div class="blog-container">
    <h1>Blog<h1>
    <p>Blog posts coming soon!</p>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">
    <h1>Contact</h1>
    <p><i class="fa fa-envelope" aria-hidden="true"></i>: lauranpham.dev@gmail.com</p>
    <div class="form-container">
    <form>
    <h3>Contact Form</h3>
            <label for="fname">First name:</label><br>
            <input type="text" id="fname" name="fname"><br>
            <label for="lname">Last name:</label><br>
            <input type="text" id="lname" name="lname"><br>
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email"><br>
            <label for="message">Message:</label><br>
            <textarea name="message" rows="5"></textarea><br><br>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

app/views/pages/home.html.erb
<div id="banner">
  <div><%= image_tag asset_path("profile_photo.JPG"), class: "avatar"%></div>
  <h1 id="heading-big">Laura Pham</h1>
  <p id="banner-p">Full-Stack Web Developer</p>
  <ul class="list-inline">
    <li>
      <a href="https://github.com/lauranpham" target="_blank"
      class= "logo">
        <i class="fab fa-github-square"></i>
      </a>
    </li>
    <li>
      <a href= "https://www.linkedin.com/in/laura-pham-641ab462" target="_blank"
      class= "logo">
        <i class="fab fa-linkedin"></i></i></a>
    </li>
    <li>
      <a href= "https://www.instagram.com/explorerlaura_/" target="_blank"
      class= "logo">
        <i class="fab fa-instagram"></i>
      </a>
    </li>
  </ul>
  <a href="#about" class="nav-arrow"><i class="fas fa-chevron-down"></i></a>
</div>

<div id="about">
    <div id="section">
    <div class="about-card">
      <h2>Full Stack Developer 💻</h2>
      <p class="description">A Full Stack Developer working in Education Tech. I enjoy the constant learning process, problem solving,
        creativity and opportunities to work with passionate, likeminded people.</p>
    </div>

    <div class="about-card">
      <h2>Teacher 📚</h2>
      <p class="description">I worked as a Science and Math teacher for three years. I hope to still make
      an impact in education through my role as a developer.</p>
    </div>

    <div class="about-card">
      <h2>Traveller 🌏</h2>
      <p class="description">Like every Australian, I am an avid world traveller. 20 countries and counting!
      I moved to London 10 months ago!</p>
    </div>
  </div>
  <a href="#projects" class="nav-arrow"><i class="fas fa-chevron-down"></i></a>
</div>

<div id="projects">
  <a href="#about" class="nav-arrow"><i class="fas fa-chevron-up"></i></a>
  <div id="projects-section">
      <h1>Recent Projects 🤓</h1>
      <div class="projects-grid">
        <div class="project-box">
        <h2 class="project-heading"> LearnerShape </h2>
        <p class="description">LearnerShape is platform the aims to transform the way we upskill and retrain using the power of Machine Learning and AI.</p>
        <a href = "http://www.learnershape.com/" target="_blank"><%= image_tag asset_path("learnershape.jpeg")%></a>
        </div>
        <div class="project-box">
          <h2 class="project-heading"> Sammi 🏫 </h2>
          <p class="description">Sammi is a supportive app for teachers to support the emotional and social development of their students.</p>
          <a href = "https://sammi.herokuapp.com/" target="_blank"><%= image_tag asset_path("sammi.jpeg")%></a>
        </div>

        <div class="project-box">
          <h2 class="project-heading"> Furreal 🐶 </h2>
          <a href=""></a>
          <p class="description">Furreal is an online marketplace to hire your next pet best friend!</p>
          <a href = "https://furreal.herokuapp.com/" target="_blank"><%= image_tag asset_path("furreal.jpeg")%></a>
          <a href=""></a>
        </div>

        <div class="project-box">
          <h2 class="project-heading"> Mister Cocktail 🍸 </h2>
          <p class="description">Mister Cocktail is a website for an up and coming bar venue with its drinks menu and prices. </p>
          <a href = "https://mister-cocktail-2311.herokuapp.com/" target="_blank"><%= image_tag asset_path("mrcocktail.jpeg")%></a>
        </div>
      </div>
    </div>
  </div>
  <a href="#projects" class="nav-arrow"><i class="fas fa-chevron-up"></i></a>
</div>

app/views/pages/projects.html.erb
<div id="projects">
  <div id="projects-section">
      <h1>Recent Projects 🤓</h1>
      <div class="projects-grid">
        <div class="project-box">
        <h2 class="project-heading"> LearnerShape </h2>
        <p class="description">LearnerShape is platform the aims to transform the way we upskill and retrain using the power of Machine Learning and AI.</p>
        <a href = "http://www.learnershape.com/" target="_blank"><%= image_tag asset_path("learnershape.jpeg")%></a>
        </div>
        <div class="project-box">
          <h2 class="project-heading"> Sammi 🏫 </h2>
          <p class="description">Sammi is a supportive app for teachers to support the emotional and social development of their students.</p>
          <a href = "https://sammi.herokuapp.com/" target="_blank"><%= image_tag asset_path("sammi.jpeg")%></a>
        </div>

        <div class="project-box">
          <h2 class="project-heading"> Furreal 🐶 </h2>
          <a href=""></a>
          <p class="description">Furreal is an online marketplace to hire your next pet best friend!</p>
          <a href = "https://furreal.herokuapp.com/" target="_blank"><%= image_tag asset_path("furreal.jpeg")%></a>
          <a href=""></a>
        </div>

        <div class="project-box">
          <h2 class="project-heading"> Mister Cocktail 🍸 </h2>
          <p class="description">Mister Cocktail is a website for an up and coming bar venue with its drinks menu and prices. </p>
          <a href = "https://mister-cocktail-2311.herokuapp.com/" target="_blank"><%= image_tag asset_path("mrcocktail.jpeg")%></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="navbar" style="font-size:20px; background-color:rgba(0,0,0,0.2);>
  <a class="navbar-brand" href="#">LP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "Home", home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Projects", projects_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Blog", blog_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>